name: CI

on:
   push:
    branches:
      - ci

jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        name: "Build for testing"
        with:
          xcode-version: '13.2.1'
      - uses: futureware-tech/simulator-action@v1
        id: simulator
        with:
          model: 'iPhone 8'
      - uses: olejnjak/carthage-workaround@v3
        with:
          action: bootstrap --cache-builds
          force: true
        run: |
          set -o pipefail && env NSUnbufferedIO=YES xcodebuild \
            -project PusherSwift.xcodeproj \
            -scheme PusherSwift \
            build \
            COMPILER_INDEX_STORE_ENABLE=NO \
            test \
            -destination "id=${{ steps.simulator.outputs.udid }}" \
            | xcpretty