name: CI

on:
   push:
    branches:
      - ci

jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        name: "Build for testing"
        with:
          xcode-version: '13.2.1'
      - uses: futureware-tech/simulator-action@v1
        id: simulator
        with:
          model: 'iPhone 8'
      - run: |
          sh ./Consumption-Tests/Shared/carthage.sh update --use-xcframeworks
          set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing \
            -project PusherSwift.xcodeproj \
            -scheme PusherSwift \
            -destination "id=${{ steps.simulator.outputs.udid }}" \
            | xcpretty 