on:
  push:
    branches: [ PS-140-release-process ]

jobs:
  check-release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3

      - name: Prepare tag
        id: prepare_tag
        continue-on-error: true
        run: |
          npm install podspec-bump
          export TAG=$(podspec-bump --dump-version -p PusherSwift.podspec)
          echo "TAG=$TAG" >> $GITHUB_ENV
          export CHECK_TAG=$(git tag | grep $TAG)
          if [[ $CHECK_TAG ]]; then
            echo "Skipping because release tag already exists"
            exit 1
          fi
      - name: Output
        id: release_output
        if: ${{ steps.prepare_tag.outcome == 'success' }}
        run: |
          echo "::set-output name=tag::${{ env.TAG }}"
    outputs:
      tag: ${{ steps.release_output.outputs.tag }}

  build:
    runs-on: macos-latest
    needs: check-release-tag
    if: ${{ needs.check-release-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sh ./Consumption-Tests/Shared/carthage.sh build --cache-builds --use-xcframeworks
  
  publish-cocoapods:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: |
          gem install cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}

  
